[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "10"

[[redirects]]
  from = "http://aiengineeringltd.com"
  to = "https://aiengineeringltd.com"
  status = 301
  force = true